/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JFAgregarHoraMedica.java
 *
 * Created on 11-12-2012, 03:38:46 PM
 */
package interfaz;

import static controlador.Principal.VETERINARIA;
import java.util.ArrayList;
import modelo.Cliente;
import modelo.HoraMedica;
import modelo.Mascota;
import modelo.MedicoVeterinario;

/**
 *
 * @author Kal-El
 */
public class JFAgregarHoraMedica extends javax.swing.JFrame {

    private HoraMedica f=new HoraMedica();
    ArrayList<Mascota> mascotasCliente=new ArrayList<Mascota>();
   // private Cliente cElegido=new Cliente();
    /** Creates new form JFAgregarHoraMedica */
    public JFAgregarHoraMedica() {
        initComponents();
        llenarListaClientes();  
        llenarListaMedicoVeterinario();
      
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jCbmes = new javax.swing.JComboBox();
        jCbdia = new javax.swing.JComboBox();
        jTagno = new javax.swing.JTextField();
        jCbHora = new javax.swing.JComboBox();
        jCbMinuto = new javax.swing.JComboBox();
        jCbclientes = new javax.swing.JComboBox();
        jCbmascota = new javax.swing.JComboBox();
        jCbmedicoVeterinario = new javax.swing.JComboBox();
        jBagregarHoraMedica = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Agregar Hora Medica");
        setMinimumSize(new java.awt.Dimension(300, 400));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos Hora Medica", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP));

        jLabel1.setText("Cliente: ");

        jLabel2.setText("Mascota: ");

        jLabel3.setText("Veterinario: ");

        jLabel4.setText("Fecha: ");

        jLabel5.setText("Hora: ");

        jCbmes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mes", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));

        jCbdia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Dia ", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        jTagno.setText("Año");

        jCbHora.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Hora", "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23" }));

        jCbMinuto.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Minuto", "00", "20", "40" }));

        jCbclientes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cliente" }));
        jCbclientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCbclientesActionPerformed(evt);
            }
        });

        jCbmascota.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mascota" }));

        jCbmedicoVeterinario.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Medico Veterinario" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jCbHora, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jCbmes, javax.swing.GroupLayout.Alignment.LEADING, 0, 62, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCbMinuto, 0, 59, Short.MAX_VALUE)
                            .addComponent(jCbdia, 0, 59, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jTagno, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jCbmascota, javax.swing.GroupLayout.Alignment.LEADING, 0, 259, Short.MAX_VALUE)
                            .addComponent(jCbclientes, javax.swing.GroupLayout.Alignment.LEADING, 0, 259, Short.MAX_VALUE)
                            .addComponent(jCbmedicoVeterinario, javax.swing.GroupLayout.Alignment.LEADING, 0, 259, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jCbclientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jCbmedicoVeterinario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jCbmascota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jCbmes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCbdia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTagno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jCbHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCbMinuto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jBagregarHoraMedica.setText("Agregar");
        jBagregarHoraMedica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBagregarHoraMedicaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jBagregarHoraMedica)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBagregarHoraMedica)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBagregarHoraMedicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBagregarHoraMedicaActionPerformed
        // TODO add your handling code here:
        
         Mascota m=(Mascota) jCbmascota.getSelectedItem(); 
         f.setMascota(m);
         
         MedicoVeterinario v=(MedicoVeterinario) jCbmedicoVeterinario.getSelectedItem();
         f.setVeterinario(v);
        
        String fecha=jCbmes.getSelectedItem().toString()+jCbdia.getSelectedItem().toString()+jTagno.getText();
        f.setFecha(fecha);
        
        String hora=jCbHora.getSelectedItem().toString()+" : "+jCbMinuto.getSelectedItem().toString();
        f.setHora(hora);
        
        VETERINARIA.agregarHora(obtenerDatosHoraMedica());
    }//GEN-LAST:event_jBagregarHoraMedicaActionPerformed

    
    public HoraMedica obtenerDatosHoraMedica(){
        return f;
    }
    
    private void jCbclientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCbclientesActionPerformed
        // TODO add your handling code here:
        Cliente cElegido=(Cliente) jCbclientes.getSelectedItem();
        f.setCliente(cElegido);     
        
        if (cElegido!=null){                
                
                VETERINARIA.llenarMascotasDeCliente(cElegido);
                mascotasCliente=cElegido.getMascota();
                
                llenarListaMascotas();
            }
    }//GEN-LAST:event_jCbclientesActionPerformed

    //llena las lista de mascota dependiendo del cliente elegido 
    private void llenarListaClientes() {
              
        for (Cliente c: VETERINARIA.getClientes()){
            jCbclientes.addItem(c);
            llenarListaMascotas(); 
            
        }
    }
    
    private void llenarListaMascotas() {
         for (Mascota mascota : mascotasCliente) {
                     jCbmascota.addItem(mascota);
                }  
        
    }
      
    private void llenarListaMedicoVeterinario() {
        for (MedicoVeterinario v: VETERINARIA.getMedicos()){
            jCbmedicoVeterinario.addItem(v);
            
        }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFAgregarHoraMedica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFAgregarHoraMedica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFAgregarHoraMedica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFAgregarHoraMedica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new JFAgregarHoraMedica().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBagregarHoraMedica;
    private javax.swing.JComboBox jCbHora;
    private javax.swing.JComboBox jCbMinuto;
    private javax.swing.JComboBox jCbclientes;
    private javax.swing.JComboBox jCbdia;
    private javax.swing.JComboBox jCbmascota;
    private javax.swing.JComboBox jCbmedicoVeterinario;
    private javax.swing.JComboBox jCbmes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTagno;
    // End of variables declaration//GEN-END:variables

    

    

    

    
}
