/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JFCMostrar.java
 *
 * Created on 06-12-2012, 05:02:06 PM
 */
package interfaz;

import javax.swing.DefaultListModel;
import modelo.Cliente;

/**
 *
 * @author Kal-El
 */
public class JFCMostrar extends javax.swing.JFrame {
    private Cliente c;
    /** Creates new form JFCMostrar */
    public JFCMostrar(Cliente c) {
        initComponents();
        this.c=c;
        
        DefaultListModel dlm = new DefaultListModel();
        
        
        if (c!=null){
            nombre.setText(c.getNombre());
            rut.setText(c.getRut());
            direccion.setText(c.getDireccion());
            telefono.setText(c.getNombre());
            email.setText(c.getEmail());
            //TODO: llenar el JList
            
//            agregarMascota.setEnabled(true);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        rut = new javax.swing.JLabel();
        nombre = new javax.swing.JLabel();
        direccion = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        telefono = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Rut");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 46, 17, 14);

        jLabel2.setText("Nombre");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 78, 37, 14);

        jLabel3.setText("Dirección");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 103, 43, 14);

        rut.setText(".");
        getContentPane().add(rut);
        rut.setBounds(139, 44, 230, 14);
        getContentPane().add(nombre);
        nombre.setBounds(297, 78, 0, 14);

        direccion.setText(".");
        getContentPane().add(direccion);
        direccion.setBounds(142, 103, 220, 10);

        jLabel4.setText("Telefono");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 128, 42, 14);

        jLabel5.setText("Email");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 153, 35, 14);

        telefono.setText(".");
        getContentPane().add(telefono);
        telefono.setBounds(142, 128, 220, 10);

        email.setText(".");
        getContentPane().add(email);
        email.setBounds(142, 153, 220, 10);

        jLabel6.setText(".");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(142, 78, 220, 10);

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 232, 156, 130);

        jLabel7.setText("Mascotas Registradas");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(100, 207, 105, 14);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void run(final Cliente c) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFCMostrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFCMostrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFCMostrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFCMostrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new JFCMostrar(c).setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel direccion;
    private javax.swing.JLabel email;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nombre;
    private javax.swing.JLabel rut;
    private javax.swing.JLabel telefono;
    // End of variables declaration//GEN-END:variables
}
