/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JFFichaMedAgregar.java
 *
 * Created on 09-12-2012, 10:50:33 PM
 */
package interfaz;

import modelo.FichaMedica;

/**
 *
 * @author Kal-El
 */
public class JFFichaMedAgregar extends javax.swing.JFrame {

    private FichaMedica h=new FichaMedica();
    
    /** Creates new form JFFichaMedAgregar */
    public JFFichaMedAgregar() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jCbdia = new javax.swing.JComboBox();
        jCbmes = new javax.swing.JComboBox();
        jTagno = new javax.swing.JTextField();
        jTid = new javax.swing.JTextField();
        jTmotivo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTaSintoma = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTaDiagnostico = new javax.swing.JTextArea();
        jBagregarHistorial = new javax.swing.JButton();
        jBsalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Agregar Ficha Medica");
        setMinimumSize(new java.awt.Dimension(600, 650));
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos Ficha Medica", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP));
        jPanel1.setLayout(null);

        jLabel1.setText("Id:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(32, 78, 42, 14);

        jLabel2.setText("Motivo:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(32, 116, 55, 14);

        jLabel3.setText("Sintomas:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(32, 151, 64, 14);

        jLabel4.setText("Diagnostico:  ");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(30, 210, 65, 14);

        jLabel5.setText("Fecha:  ");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(32, 296, 39, 14);

        jCbdia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Dia", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        jPanel1.add(jCbdia);
        jCbdia.setBounds(160, 290, 40, 20);

        jCbmes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mes", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        jPanel1.add(jCbmes);
        jCbmes.setBounds(230, 290, 44, 20);

        jTagno.setText("Año");
        jPanel1.add(jTagno);
        jTagno.setBounds(300, 290, 57, 20);
        jPanel1.add(jTid);
        jTid.setBounds(160, 70, 179, 20);
        jPanel1.add(jTmotivo);
        jTmotivo.setBounds(160, 110, 194, 20);

        jTaSintoma.setColumns(20);
        jTaSintoma.setRows(5);
        jScrollPane1.setViewportView(jTaSintoma);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(160, 140, 280, 52);

        jTaDiagnostico.setColumns(20);
        jTaDiagnostico.setRows(5);
        jScrollPane2.setViewportView(jTaDiagnostico);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(160, 210, 280, 52);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(40, 20, 450, 350);

        jBagregarHistorial.setText("Agregar");
        jBagregarHistorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBagregarHistorialActionPerformed(evt);
            }
        });
        getContentPane().add(jBagregarHistorial);
        jBagregarHistorial.setBounds(210, 380, 110, 23);

        jBsalir.setText("Salir");
        jBsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBsalirActionPerformed(evt);
            }
        });
        getContentPane().add(jBsalir);
        jBsalir.setBounds(360, 380, 100, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBagregarHistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBagregarHistorialActionPerformed
        // TODO add your handling code here:
        h.setId(jTid.getText());
        h.setMotivo(jTmotivo.getText());
        h.setSintoma(jTaSintoma.getText());
        h.setDiagnostico(jTaDiagnostico.getText());
        h.setFecha(jCbdia+"-"+jCbmes+"-"+jTagno);
        
        
    }//GEN-LAST:event_jBagregarHistorialActionPerformed

    private void jBsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBsalirActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jBsalirActionPerformed
    
    public FichaMedica obtenerDatosHistorial(){
        return h;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFFichaMedAgregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFFichaMedAgregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFFichaMedAgregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFFichaMedAgregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new JFFichaMedAgregar().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBagregarHistorial;
    private javax.swing.JButton jBsalir;
    private javax.swing.JComboBox jCbdia;
    private javax.swing.JComboBox jCbmes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTaDiagnostico;
    private javax.swing.JTextArea jTaSintoma;
    private javax.swing.JTextField jTagno;
    private javax.swing.JTextField jTid;
    private javax.swing.JTextField jTmotivo;
    // End of variables declaration//GEN-END:variables
}
