/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import controlador.Veterinaria;

/**
 *
 * @author Casa
 */
public class JFPrincipal extends javax.swing.JFrame {
    private Veterinaria veterinaria=new Veterinaria();
    /**
     * Creates new form JFVentanaGeneral
     */
    public JFPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        cAgregar = new javax.swing.JMenuItem();
        cBuscar = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mAgregar = new javax.swing.JMenuItem();
        mBuscar = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        mvAgregar = new javax.swing.JMenuItem();
        mvBuscar = new javax.swing.JMenuItem();
        mvEliminar = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        hmCrear = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        hmEliminar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Cliente");

        cAgregar.setText("Agregar");
        cAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cAgregarActionPerformed(evt);
            }
        });
        jMenu1.add(cAgregar);

        cBuscar.setText("Buscar");
        cBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cBuscarActionPerformed(evt);
            }
        });
        jMenu1.add(cBuscar);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Mascota");

        mAgregar.setText("Agregar");
        mAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mAgregarActionPerformed(evt);
            }
        });
        jMenu2.add(mAgregar);

        mBuscar.setText("Buscar");
        mBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mBuscarActionPerformed(evt);
            }
        });
        jMenu2.add(mBuscar);

        jMenuBar1.add(jMenu2);

        jMenu4.setText("Medico Veterinario");

        mvAgregar.setText("Agregar");
        mvAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mvAgregarActionPerformed(evt);
            }
        });
        jMenu4.add(mvAgregar);

        mvBuscar.setText("Buscar");
        jMenu4.add(mvBuscar);

        mvEliminar.setText("Eliminar");
        jMenu4.add(mvEliminar);

        jMenuBar1.add(jMenu4);

        jMenu3.setText("Hora Medica ");

        hmCrear.setText("Crear");
        hmCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hmCrearActionPerformed(evt);
            }
        });
        jMenu3.add(hmCrear);

        jMenuItem9.setText("Editar");
        jMenu3.add(jMenuItem9);

        hmEliminar.setText("Eliminar");
        jMenu3.add(hmEliminar);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 681, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 442, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cAgregarActionPerformed
        // TODO add your handling code here:
        JIFCAgregar agregarC=new JIFCAgregar();
        jDesktopPane1.add(agregarC);
        agregarC.setVisible(true);
        
        veterinaria.agregarCliente(agregarC.obtenerDatosCliente());
        
    }//GEN-LAST:event_cAgregarActionPerformed

    private void cBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cBuscarActionPerformed
        // TODO add your handling code here:
        JIFCBuscar buscarC=new JIFCBuscar();
        jDesktopPane1.add(buscarC);
        buscarC.setVisible(true);
                      
    }//GEN-LAST:event_cBuscarActionPerformed

    private void mAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mAgregarActionPerformed
        // TODO add your handling code here:
        JIFMAgregar agregarM=new JIFMAgregar();
        jDesktopPane1.add(agregarM);
        agregarM.setVisible(true);
        
    }//GEN-LAST:event_mAgregarActionPerformed

    private void mBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mBuscarActionPerformed
        // TODO add your handling code here:
        JIFMBuscar buscarM=new JIFMBuscar();
        jDesktopPane1.add(buscarM);
        buscarM.setVisible(true);
        
    }//GEN-LAST:event_mBuscarActionPerformed

    private void hmCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hmCrearActionPerformed
        // TODO add your handling code here:
        JIFHmCrear crearHm=new JIFHmCrear();
        jDesktopPane1.add(crearHm);
        crearHm.setVisible(true);
        
    }//GEN-LAST:event_hmCrearActionPerformed

    private void mvAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mvAgregarActionPerformed
        // TODO add your handling code here:
        JIFMvAgregar agregarMv=new JIFMvAgregar();
        jDesktopPane1.add(agregarMv);
        agregarMv.setVisible(true);
        
    }//GEN-LAST:event_mvAgregarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new JFPrincipal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem cAgregar;
    private javax.swing.JMenuItem cBuscar;
    private javax.swing.JMenuItem hmCrear;
    private javax.swing.JMenuItem hmEliminar;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenuItem mAgregar;
    private javax.swing.JMenuItem mBuscar;
    private javax.swing.JMenuItem mvAgregar;
    private javax.swing.JMenuItem mvBuscar;
    private javax.swing.JMenuItem mvEliminar;
    // End of variables declaration//GEN-END:variables
}
