/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import com.seaglasslookandfeel.SeaGlassLookAndFeel;
import static controlador.Principal.VETERINARIA;
import controlador.Veterinaria;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import modelo.HoraMedica;


/**
 *
 * @author Casa
 */
public class JFPrincipal extends javax.swing.JFrame {
    
    //creacion tabla para listar Horas medicas del dia.
    //blah blah
    DefaultTableModel listarHora = new DefaultTableModel();
    private ArrayList<HoraMedica> listaHoras= new ArrayList<HoraMedica>();
    
    /**
     * Creates new form JFVentanaGeneral
     */
    public JFPrincipal() {
        initComponents();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTListarHoras = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        cAgregar = new javax.swing.JMenuItem();
        cBuscar = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mAgregar = new javax.swing.JMenuItem();
        mBuscar = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        mvAgregar = new javax.swing.JMenuItem();
        mvBuscar = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        hmCrear = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        hmEliminar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        JTListarHoras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id.", "Cliente", "Mascota", "Veterinario", "Hora"
            }
        ));
        jScrollPane1.setViewportView(JTListarHoras);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24));
        jLabel1.setText("Consultas del Día.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 622, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(244, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(254, 254, 254))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        jPanel1.setBounds(0, 0, 700, 440);
        jDesktopPane1.add(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jMenu1.setText("Cliente");

        cAgregar.setText("Agregar");
        cAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cAgregarActionPerformed(evt);
            }
        });
        jMenu1.add(cAgregar);

        cBuscar.setText("Buscar");
        cBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cBuscarActionPerformed(evt);
            }
        });
        jMenu1.add(cBuscar);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Mascota");

        mAgregar.setText("Agregar");
        mAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mAgregarActionPerformed(evt);
            }
        });
        jMenu2.add(mAgregar);

        mBuscar.setText("Buscar");
        mBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mBuscarActionPerformed(evt);
            }
        });
        jMenu2.add(mBuscar);

        jMenuBar1.add(jMenu2);

        jMenu4.setText("Medico Veterinario");

        mvAgregar.setText("Agregar");
        mvAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mvAgregarActionPerformed(evt);
            }
        });
        jMenu4.add(mvAgregar);

        mvBuscar.setText("Buscar");
        mvBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mvBuscarActionPerformed(evt);
            }
        });
        jMenu4.add(mvBuscar);

        jMenuBar1.add(jMenu4);

        jMenu3.setText("Hora Medica ");

        hmCrear.setText("Crear");
        hmCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hmCrearActionPerformed(evt);
            }
        });
        jMenu3.add(hmCrear);

        jMenuItem9.setText("Editar");
        jMenu3.add(jMenuItem9);

        hmEliminar.setText("Eliminar");
        jMenu3.add(hmEliminar);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 708, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 589, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Funcion para mostrar datos en la tabla, posteriormente se debe de complementar en el constructor...
    public void listarHoras(ArrayList<HoraMedica> hora){
        String titulos[] = {"RUT","DV","NOMBRE","APELLIDOS","TELEFONO","EMAIL"};
        listarHora.setColumnIdentifiers(titulos);
        this.JTListarHoras.setModel(listarHora);
        this.listaHoras = hora;
    }
    
    private void cAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cAgregarActionPerformed
        // TODO add your handling code here:
        JIFCAgregar agregarC=new JIFCAgregar();
        jDesktopPane1.add(agregarC);
        agregarC.setVisible(true);
        
        
    }//GEN-LAST:event_cAgregarActionPerformed

    private void cBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cBuscarActionPerformed
        // TODO add your handling code here:
        JIFCBuscar buscarC=new JIFCBuscar();
        jDesktopPane1.add(buscarC);
        buscarC.setVisible(true);
                      
    }//GEN-LAST:event_cBuscarActionPerformed

    private void mAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mAgregarActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_mAgregarActionPerformed

    private void mBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mBuscarActionPerformed
        // TODO add your handling code here:
        JIFMBuscar buscarM=new JIFMBuscar();
        jDesktopPane1.add(buscarM);
        buscarM.setVisible(true);
        
    }//GEN-LAST:event_mBuscarActionPerformed

    private void hmCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hmCrearActionPerformed
        // TODO add your handling code here:
        JIFHmCrear crearHm=new JIFHmCrear();
        jDesktopPane1.add(crearHm);
        crearHm.setVisible(true);
        
    }//GEN-LAST:event_hmCrearActionPerformed

    private void mvAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mvAgregarActionPerformed
        // TODO add your handling code here:
        JIFMvAgregar agregarMv=new JIFMvAgregar();
        jDesktopPane1.add(agregarMv);
        agregarMv.setVisible(true);
        
    }//GEN-LAST:event_mvAgregarActionPerformed

    private void mvBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mvBuscarActionPerformed
        // TODO add your handling code here:
        JIFMvBuscar buscarMv=new JIFMvBuscar();
        jDesktopPane1.add(buscarMv);
        buscarMv.setVisible(true);
    }//GEN-LAST:event_mvBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
      
        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new JFPrincipal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JTListarHoras;
    private javax.swing.JMenuItem cAgregar;
    private javax.swing.JMenuItem cBuscar;
    private javax.swing.JMenuItem hmCrear;
    private javax.swing.JMenuItem hmEliminar;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem mAgregar;
    private javax.swing.JMenuItem mBuscar;
    private javax.swing.JMenuItem mvAgregar;
    private javax.swing.JMenuItem mvBuscar;
    // End of variables declaration//GEN-END:variables
}
